### ISSUE TITLE
Images are missing in the blogpost of the walk through

### ISSUE THREAD

**Issue by Rgghgh** [yogisec/VulnerableSAMLApp#10]
https://jellyparks.com/posts/vulnerable-saml-app/

All the images are missing, is there any way it can be fixed? can help a lot!

**Comment by yogisec** [comment]
Oh, nice catch, thanks.. I must have lost them when I migrated themes and re-arranged everything. I'll get those sorted out.

**Comment by yogisec** [comment]
Images are back now. Thanks again for the heads up.
